### ISSUE TITLE
Installing additional packages on the dask workers

### ISSUE THREAD

**Issue by Mark-S-Bartlett** [dask-contrib/dask-databricks#35]
I'd like to install additional packages on the workers. 

Typically, I'd use the following script to install packages on the dask workers:
```
from dask.distributed import Client
client = Client()
plugin = PipInstall(["xarray[io]", "dataretrieval", "earthaccess", "geopandas", "h5netcdf"], pip_options=["--upgrade"])
client.register_plugin(plugin)
```

However, when I use this code, the installed packages do not show up when I use ```client = dask_databricks.get_client()```, and conversely, I can't install the packages using the ```client``` from ```dask_databricks.get_client()```.

Any advice would be appreciated.

**Comment by Mark-S-Bartlett** [comment]
My workaround for now is to install the required libraries with the init script, e.g., 

#!/bin/bash
#Install dependencies to see if they make it to Dask:
/databricks/python/bin/pip install --upgrade xarray[io] dataretrieval earthaccess geopandas h5netcdf

# Install Dask + Dask Databricks
/databricks/python/bin/pip install --upgrade dask[complete] dask-databricks

# Start Dask cluster components
dask databricks run

**Comment by jacobtomlinson** [comment]
> I can't install the packages using the client from `dask_databricks.get_client()`

I'm curious why this isn't working. Do you get an error? Or does the installation just not take effect?

**Comment by Mark-S-Bartlett** [comment]
Actually, it does work. I probably had tried a few things yesterday, and maybe when I initially tried the deprecated ```distributed.worker.register_plugin()```, it caused issues. 

Just to document the process for installing new packages, one can use the following:

```
import dask_databricks
client = dask_databricks.get_client()
print(client.dashboard_link)

from dask.distributed import PipInstall
plugin = PipInstall(["rioxarray"], pip_options=["--upgrade"])
client.register_plugin(plugin)
```

Subsequently, one may test the install with:
```
def testinstall():
    import rioxarray
    return rioxarray.__version__

client.submit(testinstall).result()
```

**Comment by jacobtomlinson** [comment]
That's great, glad you got things working.
